
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 04 19:02:26 CEST 2010
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int LTH = 27;
  public static final int FUNCTION = 46;
  public static final int LBRACKET = 15;
  public static final int CONST = 41;
  public static final int CHAR = 9;
  public static final int SEMIC = 19;
  public static final int INT = 10;
  public static final int ARRAY = 38;
  public static final int FOR = 45;
  public static final int NOT = 31;
  public static final int AND = 21;
  public static final int RECORD = 51;
  public static final int TYPE = 54;
  public static final int NIL = 6;
  public static final int OR = 32;
  public static final int BOOL = 8;
  public static final int COMMA = 12;
  public static final int BEGIN = 40;
  public static final int DIV = 22;
  public static final int GEQ = 24;
  public static final int IF = 47;
  public static final int ASSIGN = 39;
  public static final int DOT = 13;
  public static final int PTR = 33;
  public static final int OF = 48;
  public static final int DOTS = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 17;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 50;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int ADD = 20;
  public static final int LPARENTHESIS = 16;
  public static final int NEQ = 30;
  public static final int GTH = 25;
  public static final int EQU = 23;
  public static final int COLON = 11;
  public static final int ELSE = 43;
  public static final int TO = 53;
  public static final int WHILE = 56;
  public static final int THEN = 52;
  public static final int RPARENTHESIS = 18;
  public static final int LEQ = 26;
  public static final int END = 44;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 34;
  public static final int VAR = 55;
  public static final int PROCEDURE = 49;
  public static final int DO = 42;
  public static final int IDENTIFIER = 7;

}

